import { DM_Sans } from "next/font/google";
import "./globals.css";

// COMPONENTS 

import Header from '@/components/Header/Header'
import Footer from '@/components/Footer/Footer'


// AUTH PROVIDER
import { ClerkProvider } from '@clerk/nextjs'
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import { ThemeProvider } from '@mui/material/styles';

import theme from "@/theme";

const inter = DM_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "RewFund",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider 
      publishableKey={process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
      
    >
      <html lang="en">
        <body className={inter.className}>
          <AppRouterCacheProvider options={{ key: 'css' }}>
            <ThemeProvider theme={theme} >
              <Header />
                {children}
              <Footer />
            </ThemeProvider>
          </AppRouterCacheProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}

