import { DM_Sans } from "next/font/google";
import "./globals.css";

// COMPONENTS 

import Header from '@/components/Header/Header'
import Footer from '@/components/Footer/Footer'


// AUTH PROVIDER
import { ClerkProvider } from '@clerk/nextjs'

const inter = DM_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "RewFund",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider 
      publishableKey={process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
      
    >
      <html lang="en">
        <body className={inter.className}>
          <Header />
            {children}
          <Footer />
        </body>
      </html>
    </ClerkProvider>
  );
}

